### PR TITLE
Install nfs-utils, refactor ome-k8s-pg-01

### PR DESCRIPTION
**Pull request by manics**
Install nfs-utils (needed for k8s nfs volumes), refactor ome-k8s-pg-01 variables

### CODE REVIEW

**Comment by joshmoore** [comment]
@manics : do you plan to add more here after the discussion today or is that a follow-up PR?

**Comment by manics** [comment]
This is ready for review

**Comment by joshmoore** [comment]
Check mode ran fine locally:

```
ome-k8s-pg-01.openmicroscopy.org : ok=15   changed=0    unreachable=0    failed=0
```

Happy for this to be merged, and thanks for the test. :+1:

**Comment by manics** [comment]
@joshmoore That reminds me of another benefit of splitting things by directory- it's easier to create molecule tests

**Comment by joshmoore** [comment]
Less so, I think, with the newer molecule, but that remains to be seen.

**Pull request merged**
